language: node_js
node_js:
  - stable
  - 12
  - 10
  - 8
cache: yarn

env:
  global:
    - NODE_ENV=test

install:
  - yarn install

script:
  - yarn build
  - yarn coveralls

after_success: yarn coverage
